spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/testspring2
spring.datasource.username=root
spring.datasource.password=rishab123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
